version: "1"
services:
- type: web
  name: bun-react-vite
  runtime: static
  repo: https://github.com/robdimarco-render/example-bun-app
  branch: main
  envVars:
  - key: BUN_VERSION
    value: 1.1.4 
  - key: RENDER_USE_DYNAMIC_LANGUAGE_LOADING
    value: true
  buildCommand: bun install; bun --bun vite build
  staticPublishPath: dist
  rootDir: bun-react-vite
- type: web
  name: bun-express
  runtime: node
  envVars:
  - key: BUN_VERSION
    value: 1.1.4 
  repo: https://github.com/robdimarco-render/example-bun-app
  branch: main
  plan: free
  region: oregon
  buildCommand: bun install
  startCommand: bun server.ts
  rootDir: bun-express
